import type { Theme } from "@/lib/types";

/**
 * Curated premium themes for the slide design engine.
 *
 * These themes define the FULL token surface (color + typography +
 * radius + shadow + density + image style + chart palette). Older
 * themes from `constant.ts` continue to work because resolveTheme()
 * fills missing optional fields with sensible defaults.
 *
 * Fonts are referenced by CSS variable (--font-…) declared via
 * next/font in `src/app/layout.tsx`. This keeps font loading
 * deterministic and avoids FOUT.
 */

const HEADING_SANS = "var(--font-inter-tight), 'Inter Tight', 'Inter', system-ui, -apple-system, sans-serif";
const BODY_SANS = "var(--font-inter), 'Inter', system-ui, -apple-system, sans-serif";
const HEADING_SERIF = "var(--font-fraunces), 'Fraunces', 'Iowan Old Style', Georgia, serif";
const BODY_SERIF = "var(--font-source-serif), 'Source Serif 4', 'Iowan Old Style', Georgia, serif";
const DISPLAY_CORMORANT = "var(--font-cormorant), 'Cormorant Garamond', 'Iowan Old Style', Georgia, serif";
const GEIST = "var(--font-geist-sans), 'Geist', system-ui, -apple-system, sans-serif";

export const curatedThemes: Theme[] = [
  {
    id: "minimal-white",
    name: "Minimal White",
    type: "light",
    fontFamily: BODY_SANS,
    fontHeading: HEADING_SANS,
    fontColor: "#0b0b0c",
    mutedColor: "#5b5d65",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#ffffff",
    surfaceColor: "#f6f7f9",
    accentColor: "#111827",
    accentForeground: "#ffffff",
    borderColor: "#e5e7eb",
    radius: "soft",
    shadow: "subtle",
    density: "spacious",
    imageStyle: "rounded",
    chartPalette: ["#111827", "#4b5563", "#9ca3af", "#d1d5db", "#e5e7eb"],
  },
  {
    id: "modern-dark",
    name: "Modern Dark",
    type: "dark",
    fontFamily: BODY_SANS,
    fontHeading: HEADING_SANS,
    fontColor: "#f4f4f5",
    mutedColor: "#a1a1aa",
    backgroundColor: "#09090b",
    slideBackgroundColor: "#0b0b0c",
    surfaceColor: "#151518",
    accentColor: "#fafafa",
    accentForeground: "#09090b",
    borderColor: "#27272a",
    gradientBackground: "linear-gradient(160deg, #0b0b0c 0%, #15151a 100%)",
    radius: "soft",
    shadow: "dramatic",
    density: "spacious",
    imageStyle: "rounded",
    chartPalette: ["#fafafa", "#a1a1aa", "#71717a", "#52525b", "#3f3f46"],
  },
  {
    id: "saas-blue",
    name: "SaaS Blue",
    type: "light",
    fontFamily: GEIST,
    fontHeading: GEIST,
    fontColor: "#0f172a",
    mutedColor: "#475569",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#ffffff",
    surfaceColor: "#f1f5f9",
    accentColor: "#2563eb",
    accentForeground: "#ffffff",
    borderColor: "#e2e8f0",
    radius: "soft",
    shadow: "soft",
    density: "comfortable",
    imageStyle: "rounded",
    chartPalette: ["#2563eb", "#60a5fa", "#1d4ed8", "#93c5fd", "#1e3a8a"],
  },
  {
    id: "investor-pitch",
    name: "Investor Pitch",
    type: "light",
    fontFamily: BODY_SANS,
    fontHeading: HEADING_SERIF,
    fontColor: "#1c1917",
    mutedColor: "#57534e",
    backgroundColor: "#fafaf9",
    slideBackgroundColor: "#fafaf9",
    surfaceColor: "#f5f5f4",
    accentColor: "#b45309",
    accentForeground: "#ffffff",
    borderColor: "#e7e5e4",
    radius: "sharp",
    shadow: "dramatic",
    density: "spacious",
    imageStyle: "framed",
    chartPalette: ["#b45309", "#d97706", "#92400e", "#fbbf24", "#78350f"],
  },
  {
    id: "editorial",
    name: "Editorial",
    type: "light",
    fontFamily: BODY_SERIF,
    fontHeading: HEADING_SERIF,
    fontColor: "#111111",
    mutedColor: "#555555",
    backgroundColor: "#fbfaf7",
    slideBackgroundColor: "#fbfaf7",
    surfaceColor: "#f3f1ea",
    accentColor: "#111111",
    accentForeground: "#fbfaf7",
    borderColor: "#dcd9d0",
    radius: "sharp",
    shadow: "none",
    density: "comfortable",
    imageStyle: "square",
    chartPalette: ["#111111", "#5b5b5b", "#8e8e8e", "#bdbdbd", "#dddddd"],
  },
  {
    id: "elegant-neutral",
    name: "Elegant Neutral",
    type: "light",
    fontFamily: BODY_SANS,
    fontHeading: DISPLAY_CORMORANT,
    fontColor: "#2d2a26",
    mutedColor: "#6b6259",
    backgroundColor: "#f6f1ea",
    slideBackgroundColor: "#fbf7f1",
    surfaceColor: "#efe9df",
    accentColor: "#8a6a45",
    accentForeground: "#fbf7f1",
    borderColor: "#e3dccf",
    radius: "soft",
    shadow: "soft",
    density: "comfortable",
    imageStyle: "rounded",
    chartPalette: ["#8a6a45", "#b08960", "#5f4a30", "#d4b896", "#3d2f1f"],
  },
  {
    id: "gradient-modern",
    name: "Gradient Modern",
    type: "dark",
    fontFamily: GEIST,
    fontHeading: GEIST,
    fontColor: "#f8fafc",
    mutedColor: "#cbd5e1",
    backgroundColor: "#0f0a24",
    slideBackgroundColor: "#1a1133",
    surfaceColor: "rgba(255,255,255,0.06)",
    accentColor: "#a78bfa",
    accentForeground: "#0f0a24",
    borderColor: "rgba(255,255,255,0.10)",
    gradientBackground:
      "radial-gradient(at 20% 10%, rgba(167,139,250,0.35) 0%, transparent 50%), radial-gradient(at 80% 90%, rgba(244,114,182,0.25) 0%, transparent 50%), linear-gradient(160deg, #0f0a24 0%, #2a1657 100%)",
    radius: "pill",
    shadow: "soft",
    density: "comfortable",
    imageStyle: "rounded",
    chartPalette: ["#a78bfa", "#f472b6", "#60a5fa", "#34d399", "#fbbf24"],
  },
  {
    id: "apple-style",
    name: "Apple-style",
    type: "light",
    fontFamily: BODY_SANS,
    fontHeading: HEADING_SANS,
    fontColor: "#1d1d1f",
    mutedColor: "#6e6e73",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#ffffff",
    surfaceColor: "#f5f5f7",
    accentColor: "#0071e3",
    accentForeground: "#ffffff",
    borderColor: "#d2d2d7",
    radius: "soft",
    shadow: "subtle",
    density: "spacious",
    imageStyle: "rounded",
    chartPalette: ["#0071e3", "#34c759", "#ff9500", "#ff3b30", "#5856d6"],
  },
];

export const findThemeByName = (name: string | undefined): Theme | undefined =>
  curatedThemes.find((t) => t.name === name || t.id === name);
